export const CustomStyle = {
  styleInfo: {
    '--color-brand-tertiary': '#FF8732',
    '--color-brand-primary': '#d62300',
    '--color-brand-secondary': '#d62300',
    '--color-brand-rewards': '#ff8732',
    '--color-content-primary': '#502314',
    '--color-content-secondary': '#502314',
    '--color-content-tertiary': '#3c372c',
    '--color-content-weak': '#ADA59A',
    '--color-content-default': '#D4C7B7',
    '--color-content-link': '#D62300',
    '--color-content-button': '#f5ebdc',
    '--color-content-highlight': '#502314',
    '--color-content-selection': '#502314',
    '--color-content-action': '#502314',
    '--color-content-white': '#ffffff',
    '--color-border-enabled': '#D7C7B5',
    '--color-border-disabled': '#E1D6D0',
    '--color-border-active': '#502314',
    '--color-border-brand': '#D7C7B5',
    '--color-dark': '#502314',
    '--color-light': '#F5EBDC',
    '--color-background-primary': '#ECDBC1',
    '--color-background-secondary': '#E3D9CF',
    '--color-background-tertiary': '#E3D9CF',
    '--color-background-card': '#ffffff',
    '--border-button-width': '1rpx',
  }
}